server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://libin1:8762/eureka/,http://libin:8763/eureka/
  instance:
    hostname: localhost