server:
  port: 8763

eureka:
  instance:
    hostname: libin
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://libin1:8762/eureka/